export type WorkTag = number;

export const FunctionComponent = 0; // 函数式组件
export const ClassComponent = 1; // 类组件
export const IndeterminateComponent = 2; // 在我们还不知道它是函数组件还是类组件之前
export const HostRoot = 3; // 根节点，比如说我们通过 ReactDOM.createRoot() 创建的那个 div 容器
export const HostPortal = 4; // 可能是不同渲染器的入口点的子树
export const HostComponent = 5; // 原生DOM节点
export const HostText = 6; // 原生文本节点
export const Fragment = 7; // 片段
export const Mode = 8; // 模式
export const ContextConsumer = 9; // 上下文消费者
export const ContextProvider = 10; // 上下文提供者
export const ForwardRef = 11; // 转发引用
export const Profiler = 12; // 性能分析器
export const SuspenseComponent = 13; // Suspense组件
export const MemoComponent = 14; // Memo组件
export const SimpleMemoComponent = 15; // 简单的Memo组件
export const LazyComponent = 16; // 懒加载组件
export const IncompleteClassComponent = 17; // 不完整的类组件
export const DehydratedFragment = 18; // 脱水片段
export const SuspenseListComponent = 19; // Suspense列表组件
export const ScopeComponent = 21; // 范围组件
export const OffscreenComponent = 22; // 离屏组件
export const LegacyHiddenComponent = 23; // 传统隐藏组件
export const CacheComponent = 24; // 缓存组件
export const TracingMarkerComponent = 25; // 跟踪标记组件

export const HostHoistable = 26; // 可提升的宿主组件
export const HostSingleton = 27; // 单例宿主组件
export const IncompleteFunctionComponent = 28; // 不完整的函数组件
export const Throw = 29; // 抛出组件
export const ViewTransitionComponent = 30; // 视图过渡组件
export const ActivityComponent = 31; // 活动组件
